apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrepositories.yaml
- cert-manager-release.yaml
- csi-driver-nfs-release.yaml
- external-secrets-release.yaml
- kube-prometheus-stack-values-configmap.yaml
- kube-prometheus-stack-release.yaml
- cloudnative-pg-release.yaml
- prometheus-blackbox-exporter-release.yaml
