---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./knative
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system