apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
- crds.yaml
- external-secrets.yaml
- cert-manager.yaml
- traefik.yaml
- flux-webhook.yaml
- traefik-out-of-cluster.yaml
- external-dns.yaml
- jenkins.yaml
- monitoring.yaml
- rocm.yaml
- ollama.yaml
- flux-system-additions.yaml
- jupyterhub.yaml
- searxng.yaml
- nextcloud.yaml
- hometube.yaml
# - knative.yaml
# - immich.yaml